version: "3.7"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db
    ports:
      - 5001:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      fmongo:
        ipv4_address: 172.0.0.2
  app:
    build: ./server/
    restart: always
    ports: 
      - 80:5000
    networks:
      fmongo:
        ipv4_address: 172.0.0.3
  
networks:
  fmongo:
    driver: bridge
    external: true
    internal: true